apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-hellworld-deployment
  labels:
    app: first-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-helloworld
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: first-helloworld
    spec:
      containers:
      - name: first-helloworld
        image: syhlion/helloworld
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: first-helloworld
spec:
  type: ClusterIP
  selector:
    app: first-helloworld
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
